config/routes.rb
Rails.application.routes.draw do

  # home/index/root page
  root 'front_page#index'

  # GET requests
  get '/about' => 'static_pages#about'
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'


  # POST requests
  post '/login' => 'sessions#create'

  resources :users, :param => :username
  resources :survey_completions

  # For JSON
  resources :surveys, :only => [:index, :show], :param => :name
  resources :questions, :only => [:show]

  resources :users, :only => [:show], :param => :username do
    resources :survey_completions, :only => [:new, :create, :delete]
    resources :local_surveys, :only => [:new, :create]
    resources :national_surveys, :only=> [:new, :create]
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :survey_completions, :dependent => :destroy

  validates :username, :presence => true
  validates :username, :uniqueness => true
  validates :username, :format => {
    :with => /\A[a-zA-Z0-9_-]+\z/,
    :message => "Username can only have letters, numbers, -, and _"
  }
  validates :username, :exclusion => {
    :in => %w(new edit),
    :message => "%{value} is a reserved token. Please select another username."
  }
  validates :email, :presence => true
  validates :email, :uniqueness => true
  validates :email, :format => {
    :with => /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/,
    :message => "Please enter a vaild email address."
  }
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :position, :presence => true
  validates :password, :presence => true, :on => :new
  validates :password_confirmation, :presence => true, :on => :new

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, :except => [:new, :create]
  before_action :correct_user, :except => [:new, :create]

  def show
    @user = User.find_by_username(params[:username])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new create_params

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "This is your profile!  Click on survey below to take it."
      redirect_to user_path(current_user.username)
    else
      render :new
    end
  end

  def edit
    @user = User.find_by_username params[:username]
  end

  def update
    @user = User.find_by_username params[:username]

    if @user.update_attributes update_params
      flash[:success] = "Your profile information was successfully updated."
      redirect_to user_path(@user.username)
    else
      render :edit
    end
  end

  def destroy
    user = User.find_by_username params[:username]

    if user.destroy
      flash[:success] = "Your account was successfully deleted."
      redirect_to root_path
    else
      flash[:error] = "We were unable to delete your account at this time."
      redirect_back :fallback_location => users_path(@user.username)
    end
  end

  private
    def create_params
      params.require(:user).permit(
        :username,
        :first_name,
        :last_name,
        :email,
        :password,
        :password_confirmation,
        :position
      )
    end

    def update_params
      params.require(:user).permit(
        :first_name,
        :last_name,
        :email,
        :password,
        :password_confirmation,
        :position
      )
    end

    def correct_user
      @user = User.find_by_username(params[:username])
      redirect_to root_url unless current_user? @user

    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, "Edit Profile") %>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h1>Edit my profile</h1>
    <hr style="margin-left: 30px;"/>
      <%= form_for @user, :url => user_path(@user.username), :html => { :class => "form-group" } do |f| %>
        <%= render :partial => "shared/form_errors", :locals => { :model => @user } %>

        <%= f.label "Edit your first name" %>
        <%= f.text_field :first_name, class: "form-control form-margin-bottom" %>
        <%= f.label "Edit your last name" %>
        <%= f.text_field :last_name, class: "form-control form-margin-bottom" %>
        <%= f.label "Edit your email" %>
        <%= f.text_field :email, class: "form-control form-margin-bottom" %>
        <%= f.label "Edit your position" %>
        <%= f.text_field :position, class: "form-control form-margin-bottom" %>

        <br />
  </div>
</div>
<div style = "margin: auto; text-align: center">
  <%= f.submit "Save", class: "btn btn-primary", style: "margin-right: 10px" %>
  <%= link_to "Cancel", user_path(current_user.username), class: "btn btn-cancel" %>
</div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Signup") %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>Signup</h1>
    <hr style = "margin-left: 20px"/>
    <%= form_for @user, :url => users_path, :html => { :class => "form-group" } do |f| %>
      <%= render :partial => "shared/form_errors", :locals => { :model => @user } %>

      <h4 style="text-align: center">Create a Username and Password</h4>
      <%= label_tag :username, "Username" %>
      <%= f.text_field :username, class: "form-control form-margin-bottom" %>
      <%= f.label "Password" %>
      <%= f.password_field :password, class: "form-control form-margin-bottom" %>
      <%= f.label "Retype your password" %>
      <%= f.password_field :password_confirmation, class: "form-control form-margin-bottom" %>
			<p style="text-align: center" class="cisv-orange">Please, please, please write down your password.<br>  If you lose your password, your account
				CANNOT be recovered!</p>

      <br/>
      <h4 style="text-align: center">General Information</h4>
      <%= f.label "First name" %>
      <%= f.text_field :first_name, class: "form-control form-margin-bottom" %>
      <%= f.label "Last name" %>
      <%= f.text_field :last_name, class: "form-control form-margin-bottom" %>
      <%= f.label "Your email" %>
      <%= f.text_field :email, class: "form-control form-margin-bottom" %>
      <%= label_tag :position, "What is your JB Position? "%>
        <h4 style = "display: inline;"><small>(If you have many, which one are you filling this out as?)</small></h4>
      <%= f.text_field :position, class: "form-control" %>

      <br/>
        <hr/>
      <%= f.submit "Sign Up!", class: "btn btn-primary btn-xl",
                   style: "margin: 30px auto; display: block; text-align: center" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "Profile") %>
<div class="row">

    <h1><%= @user.first_name %> <%=@user.last_name %></h1>

    <hr/>
    <div class=" container">
      <div class=" col-md-6">
        <h3>Your Information: &nbsp; <%= link_to fa_icon("pencil-square-o"), edit_user_path(@user.username) %></h3>
        <div class="table-responsive">
        <table id="profile-info-table" class="table table-striped">
          <tr>
            <td>First Name</td>
            <td><%= current_user.first_name %></td>
          </tr>
          <tr>
            <td>Last Name</td>
            <td><%= current_user.last_name %></td>
          </tr>
          <tr>
            <td>Username</td>
            <td><%= current_user.username %></td>
          </tr>
          <tr>
            <td>Email</td>
            <td><%= current_user.email %></td>
          </tr>
          <tr>
            <td>Position</td>
            <td><%= current_user.position %></td>
          </tr>
        </table>
        </div>
      </div>
      <div class="col-md-6">
        <h3>Edit or Delete Surveys Taken</h3>
        <table class = "table">
          <% if @user.survey_completions.length == 0 %>
            <tr>
              <td>None! Get started below.</td>
            </tr>
          <% else %>
            <% @user.survey_completions.order(updated_at: :desc).each do |s| %>
              <tr>

                <td><%= s.survey.name %><small>&nbsp;(<%=time_ago_in_words(s.updated_at.to_s.to_time)%>&nbsp;ago)</small>
                  <% if s.question_answers.any? { |q| q.question.required && (q.answer.blank? || q.answer == "/No Answer/") }%>
                    <small class="cisv-orange" style="font-weight: 800">(Not Completed)</small>
                  <% end%>
                </td>
                <td><%=link_to "Edit", edit_survey_completion_path(s), class: "btn btn-primary"%></td>
                <td>
                  <%= form_for s, :url =>  survey_completion_path(s), :html => { :method => :delete,} do |f|%>
                    <input type="hidden" name="survey" value="<%= s.id%>">
                    <input type = "submit" class = "btn btn-cancel" name="commit" value = "Delete">
                  <%end%>
                </td>
              </tr>
            <% end %>
							<tr><td colspan="3"><small>In order for a survey to be complete, you must answer all required questions.  You may leave other questions blank.  Selecting the "(Leave Blank)" option on multiple choice questions does NOT count as answering it.</small></td></tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
    <hr />
  <div class = "row">
    <div class = "col-md-8">
    <h3>Take a New Survey</h3>
    <table class = "table">
      <tr>
        <th>Local Surveys</th>
        <th>National Surveys</th>
        <th>Both National and Local Surveys</th>
      </tr>
      <%surveys = [[],[],[]] %>
      <% Survey.all.each do |s|
          if s.national
            if s.local
              surveys[2].push(s)
            else
              surveys[1].push(s)
            end
          else
            surveys[0].push(s) if s.local
          end
        end

        mostSurveys = 0;
        mostSurveys = surveys[0].length if surveys[0].length > mostSurveys
        mostSurveys = surveys[1].length if surveys[1].length > mostSurveys
        mostSurveys = surveys[2].length if surveys[2].length > mostSurveys
      %>
      <%mostSurveys.times do |i| %>
        <tr>
          <td>
            <% if !surveys[0][i].nil? %>
              <form action = "<%= new_user_survey_completion_path(current_user.username)%>" method="get">
                <input type="hidden" name="survey" value="<%= surveys[0][i].id%>">
                <input type = "submit" class = "btn btn-primary" name="commit" value = "<%= surveys[0][i].name %>">
              </form>
            <%end %>
          </td>
          <td>
            <% if !surveys[1][i].nil? %>
                <form action = "<%= new_user_survey_completion_path(current_user.username)%>" method="get">
                  <input type="hidden" name="survey" value="<%= surveys[1][i].id%>">
                  <input type = "submit" class = "btn btn-primary" name="commit" value = "<%= surveys[1][i].name %>">
                </form>
            <%end %>
          </td>
          <td>
            <% if !surveys[2][i].nil? %>
                <form action = "<%= new_user_survey_completion_path(current_user.username)%>" method="get">
                  <input type="hidden" name="survey" value="<%= surveys[2][i].id%>">
                  <input type = "submit" class = "btn btn-primary" name="commit" value = "<%= surveys[2][i].name %>">
                </form>
            <%end %>
          </td>
        </tr>
      <% end %>
    </table>
		</div>
</div>