config/routes.rb
Rails.application.routes.draw do

  # home/index/root page
  root 'front_page#index'

  # GET requests
  get '/about' => 'static_pages#about'
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'


  # POST requests
  post '/login' => 'sessions#create'

  resources :users, :param => :username
  resources :survey_completions

  # For JSON
  resources :surveys, :only => [:index, :show], :param => :name
  resources :questions, :only => [:show]

  resources :users, :only => [:show], :param => :username do
    resources :survey_completions, :only => [:new, :create, :delete]
    resources :local_surveys, :only => [:new, :create]
    resources :national_surveys, :only=> [:new, :create]
  end

end

app/controllers/national_surveys_controller.rb
class NationalSurveysController < ApplicationController
  before_action :set_national_survey, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user

  def index
    @national_surveys = Survey.all
  end

  def new
    @national_survey = NationalSurvey.new
    @user = User.find_by_username params[:user_username]
    return not_found("User not found!") if @user.nil?
  end

  def edit
    set_national_survey
    @user = current_user
  end

  def create
    @national_survey = NationalSurvey.new(national_survey_params)
    @user = User.find_by_username params[:user_username]
    return not_found("User not found!") if @user.nil?

    @national_survey.user = @user

    if @national_survey.save
      flash[:success] = "Your survey answers have been recorded. Thank you!"
      redirect_to user_path(@user.username)
    else
      render :new
    end
  end

  def update
    @user = current_user
    @national_survey = @user.national_survey

    if @national_survey.update_attributes national_survey_params
      flash[:success] = "Your survey answers have been updated."
      redirect_to user_path(current_user.username)
    else
      render :edit
    end
  end

  def destroy
  end

  private
  def set_national_survey
    @national_survey = Survey.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def national_survey_params
    params.require(:national_survey).permit(:jb_region, :jb_neighborhood, :num_chapters, :national_jb, :leadership_composition, :national_events, :num_active, :num_active_national, :gender_ratio, :S3Q1, :S3Q2, :S3Q3, :S3Q4, :S3Q5, :S3P1Q1, :S3P1Q2, :S3P1Q3, :S3P1Q4, :S3P1Q4, :S3P1Q5, :S3P1Q6, :S3P2Q1, :S3P2Q2, :S3P2Q3, :S3P2Q4, :S3P2Q5, :S4P1Q1, :S4P1Q2, :S4P2Q1, :S4P2Q2, :S4P3Q1, :S4P3Q2, :S4P3Q3, :S4P3Q4, :S4P4Q1, :S4P4Q2, :S4P4Q3, :S4P4Q4, :S5Q1, :S5Q2, :S6Q1, :S6Q2)
  end

end

app/helpers/national_surveys_helper.rb
module NationalSurveysHelper
end

app/views/national_surveys/_form.html.erb
<%= form_for(national_survey) do |f| %>

  <div class="field">
    <%= f.label "Please select your JB Region." %>
    <%= f.text_field :jb_region %>
  </div>

  <div class="field">
    <%= f.label "Please select your JB Neighborhood." %>
    <%= f.text_field :jb_neighborhood %>
  </div>

  <div class="field">
    <%= f.label "Select your number of chapters." %>
    <%= f.number_field :num_chapters %>
  </div>

  <div class="field">
    <%= f.label "Select your national JB." %>
    <%= f.text_field :national_jb %>
  </div>

  <div class="field">
    <%= f.label "Please describe the leadership/composition of national JB board, if you have one." %>
    <%= f.text_field :leadership_composition %>
  </div>

  <div class="field">
    <%= f.label "How many national JB events do you have per year?" %>
    <%= f.number_field :national_events %>
  </div>

  <div class="field">
    <%= f.label "How many JBers, on average, are active participants in your JB?" %>
    <%= f.number_field :num_active %>
  </div>

  <div class="field">
    <%= f.label "How many JBers, on average, are active participants in your national JB?" %>
    <%= f.number_field :num_active_national %>
  </div>

  <div class="field">
    <%= f.label "Would you say your National JB is composed of more:" %>
    <%= f.text_field :gender_ratio %>
  </div>

  <div class="field">
    <%= f.label "The relationship between my JB and my CISV NA/PA's board is good." %>
    <%= f.check_box :S3Q1 %>
  </div>

  <div class="field">
    <%= f.label "My JB participates in neighborhood projects." %>
    <%= f.check_box :S3Q2 %>
  </div>

  <div class="field">
    <%= f.label "How many JBers from your NA have attended your most recent neighborhood workshop?" %>
    <%= f.number_field :S3Q3 %>
  </div>

  <div class="field">
    <%= f.label "My JB participates in regional projects." %>
    <%= f.check_box :S3Q4 %>
  </div>

  <div class="field">
    <%= f.label "How many JBers from your NA attended your most recent regional meeting?" %>
    <%= f.number_field :S3Q5 %>
  </div>

  <div class="field">
    <%= f.label "As NJRs, we constantly are always in touch with our Junior Branch Regional Team (e.g. AJB Team, APJB Team, EJB Team)." %>
    <%= f.check_box :S3P1Q1 %>
  </div>

  <div class="field">
    <%= f.label "Our coordinator and our regional team represent us." %>
    <%= f.check_box :S3P1Q2 %>
  </div>

  <div class="field">
    <%= f.label "The regional team is responsive to our needs." %>
    <%= f.check_box :S3P1Q3 %>
  </div>

  <div class="field">
    <%= f.label "Tools and information provided by the regional team are useful and helpful." %>
    <%= f.check_box :S3P1Q4 %>
  </div>

  <div class="field">
    <%= f.label "Our coordinator is up to date with our national JB." %>
    <%= f.check_box :S3P1Q5 %>
  </div>

  <div class="field">
    <%= f.label "We are up to date with the work of our Regional team." %>
    <%= f.check_box :S3P1Q6 %>
  </div>

  <div class="field">
    <%= f.label "My JB Participates in international projects (e.g. Branch out, Dig In... Please specify)." %>
    <%= f.check_box :S3P2Q1 %>
  </div>

  <div class="field">
    <%= f.label "We feel that the work developed by IJB Team contributes to our national JB." %>
    <%= f.check_box :S3P2Q2 %>
  </div>

  <div class="field">
    <%= f.label "How many JBers from your NA attended the last IJBC (International Junior Branch Conference)?" %>
    <%= f.number_field :S3P2Q3 %>
  </div>

  <div class="field">
    <%= f.label "Funded, Partially funded, Not funded" %>
    <%= f.text_field :S3P2Q4 %>
  </div>

  <div class="field">
    <%= f.label "If yes, by whom were the funded?" %>
    <%= f.text_field :S3P2Q5 %>
  </div>

  <div class="field">
    <%= f.label "As NJRs, we constatnly communicate with the LJRs." %>
    <%= f.check_box :S4P1Q1 %>
  </div>

  <div class="field">
    <%= f.label "Which are the most effective methods of communication you use to keep in touch with LJRs?" %>
    <%= f.text_field :S4P1Q2 %>
  </div>

  <div class="field">
    <%= f.label "In 2015, Educational Content was very explored at our national trainings/workshops/meetings." %>
    <%= f.check_box :S4P2Q1 %>
  </div>

  <div class="field">
    <%= f.label "Our national JB develops consistent Educational Content projects." %>
    <%= f.check_box :S4P2Q2 %>
  </div>

  <div class="field">
    <%= f.label "Does your national JB have a national training for JBers?" %>
    <%= f.check_box :S4P3Q1 %>
  </div>

  <div class="field">
    <%= f.label "Does your national JB have a specific trainings for LJRs?" %>
    <%= f.check_box :S4P3Q2 %>
  </div>

  <div class="field">
    <%= f.label "Does your national JB have trainings for local JBs?" %>
    <%= f.check_box :S4P3Q3 %>
  </div>

  <div class="field">
    <%= f.label "Does your national JB have documents to describe the role of a JB?" %>
    <%= f.check_box :S4P3Q4 %>
  </div>

  <div class="field">
    <%= f.label "Our national JB does a consistent yearly evaluation." %>
    <%= f.check_box :S4P4Q1 %>
  </div>

  <div class="field">
    <%= f.label "Our national JB does a yearly strategic planning." %>
    <%= f.check_box :S4P4Q2 %>
  </div>

  <div class="field">
    <%= f.label "Our national JB follows the development of local JBs during the year." %>
    <%= f.check_box :S4P4Q3 %>
  </div>

  <div class="field">
    <%= f.label "Do the NJRs have a Midway-Meeting? Online, In-person, No" %>
    <%= f.text_field :S4P4Q4 %>
  </div>

  <div class="field">
    <%= f.label "Do you know who your National Risk Manager is?" %>
    <%= f.check_box :S5Q1 %>
  </div>

  <div class="field">
    <%= f.label "Our national Risk Manager is aware of all the activities organized by the JB." %>
    <%= f.check_box :S5Q2 %>
  </div>

  <div class="field">
    <%= f.label "Do you have any recommendations or comments for the JB set group?" %>
    <%= f.text_field :S6Q1 %>
  </div>

  <div class="field">
    <%= f.label "Does filling JB SET help your JB somehow? If yes, how? If not, why?" %>
    <%= f.text_field :S6Q2 %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/national_surveys/edit.html.erb
<% provide(:title, "Edit National Survey") %>
<h1>Editing National Survey</h1>
<hr />

<%= form_for @national_survey, class: "form-group" do |f| %>
<%= render :partial => "shared/form_errors", :locals => { :model => @national_survey } %>

    <%= f.label "Enter your JB Region." %>
    <%= f.text_field :jb_region, class: "form-control form-margin-bottom" %>

    <%= f.label "Enter your JB Neighborhood." %>
    <%= f.text_field :jb_neighborhood, class: "form-control form-margin-bottom" %>

    <%= f.label "Enter your number of chapters." %>
    <%= f.number_field :num_chapters, class: "form-control form-margin-bottom" %>

    <%= f.label "Enter your national JB." %>
    <%= f.text_field :national_jb, class: "form-control form-margin-bottom" %>

    <%= f.label "Describe the leadership/composition of national JB board, if you have one." %>
    <%= f.text_field :leadership_composition, class: "form-control form-margin-bottom" %>

    <%= f.label "How many national JB events do you have per year?" %>
    <%= f.number_field :national_events, class: "form-control form-margin-bottom" %>

    <%= f.label "How many JBers, on average, are active participants in your JB?" %>
    <%= f.number_field :num_active, class: "form-control form-margin-bottom" %>

    <%= f.label "How many JBers, on average, are active participants in your national JB?" %>
    <%= f.number_field :num_active_national, class: "form-control form-margin-bottom" %>

    <%= f.label "My local JB is composed of more " %>
    <br />
    <%= f.select :gender_ratio, [['select', nil], ['male', 'male'], ['female', 'female'], ['It is very balanced', 'It is very balanced']],  {class: "form-control form-margin-bottom"} %>
    <br /><br />

    <%= f.label "The relationship between my JB and my CISV NA/PA's board is good." %>
    <br />
    <%= f.select :S3Q1,[['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "My JB participates in neighborhood projects." %>
    <br />
    <%= f.select :S3Q2, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "How many JBers from your NA have attended your most recent neighborhood workshop?" %>
    <%= f.number_field :S3Q3, class: "form-control form-margin-bottom" %>

    <%= f.label "My JB participates in regional projects." %>
    <br />
    <%= f.select :S3Q4, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "How many JBers from your NA attended your most recent regional meeting?" %>
    <%= f.number_field :S3Q5, class: "form-control form-margin-bottom" %>

    <%= f.label "As NJRs, we are always in touch with our Junior Branch Regional Team (e.g. AJB Team, APJB Team, EJB Team)." %>
    <br />
    <%= f.select :S3P1Q1, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Our coordinator and our regional team represent us." %>
    <br />
    <%= f.select :S3P1Q2, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "The regional team is responsive to our needs." %>
    <br />
    <%= f.select :S3P1Q3, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Tools and information provided by the regional team are useful and helpful." %>
    <br />
    <%= f.select :S3P1Q4, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Our coordinator is up to date with our national JB." %>
    <br />
    <%= f.select :S3P1Q5, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "We are up to date with the work of our Regional team." %>
    <br />
    <%= f.select :S3P1Q6, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "My JB Participates in international projects (e.g. Branch out, Dig In... Please specify)." %>
    <br />
    <%= f.select :S3P2Q1, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "We feel that the work developed by IJB Team contributes to our national JB." %>
    <br />
    <%= f.select :S3P2Q2, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "How many JBers from your NA attended the last IJBC (International Junior Branch Conference)?" %>
    <%= f.number_field :S3P2Q3, class: "form-control form-margin-bottom" %>

    <%= f.label "We are " %>
    <br />
    <%= f.select :S3P2Q4, [['select', nil], ['funded', 'funded'], ['partially funded', 'partially funded'], ['not funded', 'not funded']], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "If yes, by whom are you funded?" %>
    <%= f.text_field :S3P2Q5, class: "form-control form-margin-bottom" %>

    <%= f.label "As NJRs, we constatnly communicate with the LJRs." %>
    <br />
    <%= f.select :S4P1Q1, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Which are the most effective methods of communication you use to keep in touch with LJRs?" %>
    <%= f.text_field :S4P1Q2, class: "form-control form-margin-bottom" %>

    <%= f.label "In 2015, Educational Content was very explored at our national trainings/workshops/meetings." %>
    <br /><
    <%= f.select :S4P2Q1, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Our national JB develops consistent Educational Content projects." %>
    <br />
    <%= f.select :S4P2Q2, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Our national JB has a national training for JBers." %>
    <br />
    <%= f.select :S4P3Q1, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Our national JB has a specific trainings for LJRs." %>
    <br />
    <%= f.select :S4P3Q2, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Our national JB have trainings for local JBs." %>
    <br />
    <%= f.select :S4P3Q3, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Our national JB has documents to describe the role of a JB." %>
    <br />
    <%= f.select :S4P3Q4, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Our national JB does a consistent yearly evaluation." %>
    <br />
    <%= f.select :S4P4Q1, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Our national JB does a yearly strategic planning." %>
    <br />
    <%= f.select :S4P4Q2, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom"%>
    <br /><br />


    <%= f.label "Our national JB follows the development of local JBs during the year." %>
    <br />
    <%= f.select :S4P4Q3, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "The NJRs have a Midway-Meeting? Online, In-person, No" %>
    <br />
    <%= f.select :S4P4Q4, [['select', nil], ['Midway-Meeting', 'Midway-Meeting'], ['Online', 'Online'], ['Neither', 'Neither']], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Do you know who your National Risk Manager is?" %>
    <br />
    <%= f.select :S5Q1, [['select', nil], ['yes', 'yes'], ['no', 'no']], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Our national Risk Manager is aware of all the activities organized by the JB." %>
    <br />
    <%= f.select :S5Q2, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Please provide any recommendations or comments for the JB set group." %>
    <%= f.text_field :S6Q1, class: "form-control form-margin-bottom" %>

    <%= f.label "Does filling JB SET help your JB somehow? If yes, how? If not, why?" %>
    <%= f.text_field :S6Q2, class: "form-control form-margin-bottom" %>

  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%= link_to "Cancel", user_path(current_user.username), class: "btn btn-danger" %>
<% end %>

app/views/national_surveys/new.html.erb
<% provide(:title, "National Survey") %>
<h1>New National Survey</h1>
<hr />

<%= form_for @national_survey, :url => user_national_surveys_path(@user.username), class: "form-group" do |f| %>
<%= render :partial => "shared/form_errors", :locals => { :model => @national_survey } %>

    <%= f.label "Enter your JB Region." %>
    <%= f.text_field :jb_region, class: "form-control form-margin-bottom" %>

    <%= f.label "Enter your JB Neighborhood." %>
    <%= f.text_field :jb_neighborhood, class: "form-control form-margin-bottom" %>

    <%= f.label "Enter your number of chapters." %>
    <%= f.number_field :num_chapters, class: "form-control form-margin-bottom" %>

    <%= f.label "Enter your national JB." %>
    <%= f.text_field :national_jb, class: "form-control form-margin-bottom" %>

    <%= f.label "Describe the leadership/composition of national JB board, if you have one." %>
    <%= f.text_field :leadership_composition, class: "form-control form-margin-bottom" %>

    <%= f.label "How many national JB events do you have per year?" %>
    <%= f.number_field :national_events, class: "form-control form-margin-bottom" %>

    <%= f.label "How many JBers, on average, are active participants in your JB?" %>
    <%= f.number_field :num_active, class: "form-control form-margin-bottom" %>

    <%= f.label "How many JBers, on average, are active participants in your national JB?" %>
    <%= f.number_field :num_active_national, class: "form-control form-margin-bottom" %>

    <%= f.label "My local JB is composed of more " %>
    <br />
    <%= f.select :gender_ratio, [['select', nil], ['male', 'male'], ['female', 'female'], ['It is very balanced', 'It is very balanced']],  {class: "form-control form-margin-bottom"} %>
    <br /><br />

    <%= f.label "The relationship between my JB and my CISV NA/PA's board is good." %>
    <br />
    <%= f.select :S3Q1,[['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "My JB participates in neighborhood projects." %>
    <br />
    <%= f.select :S3Q2, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "How many JBers from your NA have attended your most recent neighborhood workshop?" %>
    <%= f.number_field :S3Q3, class: "form-control form-margin-bottom" %>

    <%= f.label "My JB participates in regional projects." %>
    <br />
    <%= f.select :S3Q4, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "How many JBers from your NA attended your most recent regional meeting?" %>
    <%= f.number_field :S3Q5, class: "form-control form-margin-bottom" %>

    <%= f.label "As NJRs, we are always in touch with our Junior Branch Regional Team (e.g. AJB Team, APJB Team, EJB Team)." %>
    <br />
    <%= f.select :S3P1Q1, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Our coordinator and our regional team represent us." %>
    <br />
    <%= f.select :S3P1Q2, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "The regional team is responsive to our needs." %>
    <br />
    <%= f.select :S3P1Q3, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Tools and information provided by the regional team are useful and helpful." %>
    <br />
    <%= f.select :S3P1Q4, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Our coordinator is up to date with our national JB." %>
    <br />
    <%= f.select :S3P1Q5, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "We are up to date with the work of our Regional team." %>
    <br />
    <%= f.select :S3P1Q6, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "My JB Participates in international projects (e.g. Branch out, Dig In... Please specify)." %>
    <br />
    <%= f.select :S3P2Q1, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "We feel that the work developed by IJB Team contributes to our national JB." %>
    <br />
    <%= f.select :S3P2Q2, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "How many JBers from your NA attended the last IJBC (International Junior Branch Conference)?" %>
    <%= f.number_field :S3P2Q3, class: "form-control form-margin-bottom" %>

    <%= f.label "We are " %>
    <br />
    <%= f.select :S3P2Q4, [['select', nil], ['funded', 'funded'], ['partially funded', 'partially funded'], ['not funded', 'not funded']], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "If yes, by whom are you funded?" %>
    <%= f.text_field :S3P2Q5, class: "form-control form-margin-bottom" %>

    <%= f.label "As NJRs, we constatnly communicate with the LJRs." %>
    <br />
    <%= f.select :S4P1Q1, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Which are the most effective methods of communication you use to keep in touch with LJRs?" %>
    <%= f.text_field :S4P1Q2, class: "form-control form-margin-bottom" %>

    <%= f.label "In 2015, Educational Content was very explored at our national trainings/workshops/meetings." %>
    <br /><
    <%= f.select :S4P2Q1, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Our national JB develops consistent Educational Content projects." %>
    <br />
    <%= f.select :S4P2Q2, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Our national JB has a national training for JBers." %>
    <br />
    <%= f.select :S4P3Q1, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Our national JB has a specific trainings for LJRs." %>
    <br />
    <%= f.select :S4P3Q2, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Our national JB have trainings for local JBs." %>
    <br />
    <%= f.select :S4P3Q3, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Our national JB has documents to describe the role of a JB." %>
    <br />
    <%= f.select :S4P3Q4, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Our national JB does a consistent yearly evaluation." %>
    <br />
    <%= f.select :S4P4Q1, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Our national JB does a yearly strategic planning." %>
    <br />
    <%= f.select :S4P4Q2, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom"%>
    <br /><br />


    <%= f.label "Our national JB follows the development of local JBs during the year." %>
    <br />
    <%= f.select :S4P4Q3, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "The NJRs have a Midway-Meeting? Online, In-person, No" %>
    <br />
    <%= f.select :S4P4Q4, [['select', nil], ['Midway-Meeting', 'Midway-Meeting'], ['Online', 'Online'], ['Neither', 'Neither']], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Do you know who your National Risk Manager is?" %>
    <br />
    <%= f.select :S5Q1, [['select', nil], ['yes', 'yes'], ['no', 'no']], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Our national Risk Manager is aware of all the activities organized by the JB." %>
    <br />
    <%= f.select :S5Q2, [['select', nil], ['true', true], ['false', false]], class: "form-control form-margin-bottom" %>
    <br /><br />

    <%= f.label "Please provide any recommendations or comments for the JB set group." %>
    <%= f.text_field :S6Q1, class: "form-control form-margin-bottom" %>

    <%= f.label "Does filling JB SET help your JB somehow? If yes, how? If not, why?" %>
    <%= f.text_field :S6Q2, class: "form-control form-margin-bottom" %>

  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%= link_to "Cancel", user_path(current_user.username), class: "btn btn-danger" %>
<% end %>

app/views/national_surveys/show.html.erb
<%= render :partial =>  "national_surveys/national_survey.json" %>