config/routes.rb
Rails.application.routes.draw do

  # home/index/root page
  root 'front_page#index'

  # GET requests
  get '/about' => 'static_pages#about'
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'


  # POST requests
  post '/login' => 'sessions#create'

  resources :users, :param => :username
  resources :survey_completions

  # For JSON
  resources :surveys, :only => [:index, :show], :param => :name
  resources :questions, :only => [:show]

  resources :users, :only => [:show], :param => :username do
    resources :survey_completions, :only => [:new, :create, :delete]
    resources :local_surveys, :only => [:new, :create]
    resources :national_surveys, :only=> [:new, :create]
  end

end

app/models/survey_completion.rb
class SurveyCompletion < ApplicationRecord
  belongs_to :user
  belongs_to :survey
  has_many :question_answers, :dependent => :destroy

  validates :user_id, presence: true
  validates :survey_id, presence: true

end

app/controllers/survey_completions_controller.rb
class SurveyCompletionsController < ApplicationController
  before_action :authenticate_user

  def new
    @survey_completion = current_user.survey_completions.new survey_id: params[:survey]
    @questions = Survey.find(params[:survey]).questions
    @questions = @questions.sort_by &:qorder
    require 'csv'
    @countryNames = Array.new
    CSV.read("#{Rails.root}/app/assets/images/jb-countries.tsv", {:col_sep => "\t"}).each do |c|
      @countryNames.push(c[1])
    end
    @countryNames.shift 1;
    @countryNames.sort!


  end

  def create
    @survey_completion = current_user.survey_completions.new
    @survey_completion.country = params[:survey_completion][:country]
    @survey_completion.survey = Survey.find(params[:survey_id])
    if @survey_completion.save
      #Save all those questions.
        params[:questionAnswer].each do |question, answer|
          questionAnswer = @survey_completion.question_answers.new
          questionAnswer.question = Question.find(question)
          questionAnswer.answer = answer
          questionAnswer.survey_completion = @survey_completion
          unless questionAnswer.save
            flash["alert-danger"] = "An answer was unable to be saved."
          end
        end

      flash[:success] = "Awesome.  Your answers have been saved.  You can edit them at any time."
      redirect_to user_path(current_user.username)
    else
      flash[:warning] = "Aw shit it didn't save"
    end
  end

  def edit
    @survey_completion = SurveyCompletion.find(params[:id])
    @questionsAnswers = SurveyCompletion.find(params[:id]).question_answers.sort_by {|e| e.question.qorder}
    @questions = SurveyCompletion.find(params[:id]).survey.questions.sort_by{|e| e.qorder}
    @countryNames = Array.new
    require 'csv'
    CSV.read("#{Rails.root}/app/assets/images/jb-countries.tsv", {:col_sep => "\t"}).each do |c|
      @countryNames.push(c[1])
    end
    @countryNames.shift 1;
    @countryNames.sort!

    unless @survey_completion.user == current_user
      redirect_to user_path(current_user.username)
    end
  end

  def update
    @survey_completion = SurveyCompletion.find(params[:id])
    # a naive hack so that it updates the updated_at column every time
    @survey_completion.update country: "fake country"
    @survey_completion.update country: params[:survey_completion][:country]
    if @survey_completion.valid?
      #Save all those questions.
      @survey_completion.question_answers.each {|q| q.destroy}
      params[:questionAnswer].each do |question, answer|
        questionAnswer = @survey_completion.question_answers.new
        questionAnswer.question = Question.find(question)
        questionAnswer.answer = answer
        questionAnswer.survey_completion = @survey_completion
        unless  questionAnswer.save
          flash["alert-danger"] = "An answer was unable to be saved."
        end
      end

      flash[:success] = "Thanks! Your answers have been saved."
      redirect_to user_path(current_user.username)
    else
      flash["alert-danger"] = "Something went wrong, it didn't save."
    end
  end

  def destroy
    survey_completion = SurveyCompletion.find(params[:survey])
    if survey_completion.user == current_user
      if SurveyCompletion.find(params[:survey]).destroy
        flash[:success] = "Answers successfully deleted"
        redirect_to user_path(current_user.username)
      else
        flash["alert-danger"] = "Something went wrong. Answers not deleted."
        redirect_to user_path(current_user.username)
      end
    else
      flash["alert-danger"] = "You don't have access to that page"
      redirect_to user_path(current_user.username)
    end
  end
end

app/helpers/survey_completions_helper.rb
module SurveyCompletionsHelper
end

app/views/survey_completions/destroy.html.erb
<h1>SurveyCompletions#destroy</h1>
<p>Find me in app/views/survey_completions/destroy.html.erb</p>

app/views/survey_completions/edit.html.erb
<%provide :title, "Edit"<<@survey_completion.survey.name %>
<div class ="row">
  <div class = "col-md-8 col-md-offset-2">
    <h1>Edit <%= @survey_completion.survey.name%></h1>
		 <hr style = "margin-left: 30px"/>

		<p class = "about"> <%=@survey_completion.survey.about%></p>

    <%= form_for @survey_completion, :html => {class: "form-group"} do |f| %>
        <input type = "hidden" name = "survey_id" value = "<%= @survey_completion.survey.id%>">
        <% if @survey_completion.survey.national %>
            <%= label_tag :country, "About which country are you filling out this survey?" %>
        <% else %>
            <%= label_tag :country, "Which country is this chapter in?" %>
        <% end %>
        <select id="survey_completion_country" name= "survey_completion[country]"  class="form-control form-margin-bottom" >
          <%= options_for_select(@countryNames, @survey_completion.country)%>
        </select>

        <% @questionsAnswers.each do |a| %>
            <div class = "question">
            <%q = a.question%>
		    <%if q.qtype != 'mc' && q.qtype != 'h'%>
				<label for="<%=q.id%>">
					<%= q.name%>
					<%if q.required %>
					<span class = "required-text">*Required</span>
					<%end%>
				</label>
			<%end%>
            <% case q.qtype %>
            <% when 'lr' #longresponse %>
                <textarea id="<%=q.id%>" name = "questionAnswer[<%=q.id%>]" rows ="5" class = "form-control form-margin-bottom" ><%=a.answer%></textarea>

            <% when 'sr' #shortresponse %>
                <input id="<%=q.id%>" value = "<%=a.answer%>" type="text" name = "questionAnswer[<%=q.id%>]" class = "form-control form-margin-bottom">

            <% when 'mc' #multiple-choice %>
                <%questionInfo = q.name.partition("[CHOICES]") %>
                   <label for="<%=q.id%>"><%= questionInfo.first%>
					<%if q.required %>
						<span class = "required-text">*Required</span>
					<%end%>
					</label>
                <%questionInfo.last.split("|").each do |choice| %>
                    <div class = "form-check">
                      <label class="form-check-label thin">
                        <input class = "form-check-input" <%= "checked = 'checked'" if choice==a.answer%> type = "radio" name = "questionAnswer[<%=q.id%>]" value="<%=choice%>">
                        <%=choice%>
                      </label>
                    </div>
                <%end%>
                <div class = "form-check form-margin-bottom">
                  <label class="form-check-label ">
                    <input class = "form-check-input" <%= "checked = 'checked'" if '/No Answer/' == a.answer%> type = "radio" name = "questionAnswer[<%=q.id%>]" value="/No Answer/">
                   (Leave Blank)
                  </label>
                </div>

            <% when 'yn' #yes-no %>
                <div class = "form-check">
                  <label class ="form-check-label thin">
                    <input class = "form-check-input" <%= "checked = 'checked'" if 'Yes' == a.answer%> type = "radio" name = "questionAnswer[<%=q.id%>]" value = "Yes">
                    Yes
                  </label>
                </div>
                <div class = "form-check">
                  <label class ="form-check-label thin">
                    <input class = "form-check-input" <%= "checked = 'checked'" if 'No' == a.answer%> type = "radio" name = "questionAnswer[<%=q.id%>]" value = "No">
                    No
                  </label>
                </div>
                <div class = "form-check form-margin-bottom">
                  <label class ="form-check-label">
                    <input class = "form-check-input" <%= "checked = 'checked'" if '/No Answer/' == a.answer%> type = "radio" name = "questionAnswer[<%=q.id%>]" value = "/No Answer/">
                   (Leave Blank)
                  </label>
                </div>

            <% when 'tf' #true-false %>
                <div class = "form-check">
                  <label class ="form-check-label thin">
                    <input class = "form-check-input" <%= "checked = 'checked'" if 'True' == a.answer%> type = "radio" name = "questionAnswer[<%=q.id%>]" value = "True">
                    True
                  </label>
                </div>
                <div class = "form-check">
                  <label class ="form-check-label thin">
                    <input class = "form-check-input" <%= "checked = 'checked'" if 'False' == a.answer%> type = "radio" name = "questionAnswer[<%=q.id%>]" value = "False">
                    False
                  </label>
                  <div class = "form-check form-margin-bottom">
                    <label class ="form-check-label">
                      <input class = "form-check-input" <%= "checked = 'checked'" if '/No Answer/' == a.answer%> type = "radio" name = "questionAnswer[<%=q.id%>]" value = "/No Answer/">
                     (Leave Blank)
                    </label>
                  </div>
                </div>
            <% when 'n' #number %>
                <input id="<%=q.id%>" type="number" value = "<%= a.answer%>" name = "questionAnswer[<%=q.id%>]" class = "form-control form-margin-bottom" placeholder="Please enter a number">
            <% when 'h' #header %>
                <h3 class = "text-center"><%=q.name%></h3>
								<input id="<%=q.id%>" name = "questionAnswer[<%=q.id%>]" style="display: none;"> 

                <hr />
            <%end%>
            </div>
        <% end %>
        <div style = "margin: 30px auto; display: block; text-align: center">
          <%= f.submit "Save Edits", class: "btn btn-primary" %>
          <%= link_to "Cancel", user_path(current_user.username), class: "btn btn-cancel" %>
        </div>
    <% end %>

  </div>
</div>

<script>
    boldChoice();
    window.addEventListener('click', boldChoice);
    function boldChoice(){
        var inputs = document.getElementsByClassName('form-check-input');
        for(var i = 0; i<inputs.length; i++){
            e = inputs.item(i);
            if(e.checked){
                e.parentNode.classList.remove('thin');
            }
            else{
                e.parentNode.classList.add('thin')
            }
        }
    }
</script>

app/views/survey_completions/new.html.erb
<%provide :title, @survey_completion.survey.name %>
<div class ="row">
  <div class = "col-md-8 col-md-offset-2">
    <h1><%= @survey_completion.survey.name%></h1>
    <hr style = "margin-left: 30px"/>
		<p class = 'about'><%=@survey_completion.survey.about%></p>
    <%= form_for @survey_completion, :url => user_survey_completions_path, :html => {class: "form-group"} do |f| %>
        <input type = "hidden" name = "survey_id" value = "<%= @survey_completion.survey.id%>">
      <% if @survey_completion.survey.national %>
          <%= label_tag :country, "About which country are you filling out this survey?" %>
      <% else %>
          <%= label_tag :country, "Which country is your chapter in?" %>
      <% end %>

      <select id="survey_completion_country" name= "survey_completion[country]"  class="form-control form-margin-bottom" >
        <%= options_for_select(@countryNames)%>
      </select>
      <% @questions.each do |q| %>
            <div class = "question">
			<%if q.qtype != 'mc' && q.qtype != 'h'%>
				<label for="<%=q.id%>">
					<%= q.name%>
					<%if q.required %>
					<span class = "required-text">*Required</span>
					<%end%>
				</label>
			<%end%>
            <% case q.qtype %>
             <% when 'lr' #longresponse %>
                <textarea id="<%=q.id%>" name = "questionAnswer[<%=q.id%>]" rows ="5" class = "form-control form-margin-bottom" ></textarea>
             <% when 'sr' #shortresponse %>
                <input id="<%=q.id%>" type="text" name = "questionAnswer[<%=q.id%>]" class = "form-control form-margin-bottom">
             <% when 'mc' #multiple-choice %>
                <%questionInfo = q.name.partition("[CHOICES]") %>
                   <label for="<%=q.id%>"><%= questionInfo.first%>
					<%if q.required %>
						<span class = "required-text">*Required</span>
					<%end%>
					</label>
                <%questionInfo.last.split("|").each do |choice| %>
                    <div class = "form-check">
                        <label class="form-check-label thin">
                          <input class = "form-check-input" type = "radio" name = "questionAnswer[<%=q.id%>]" value="<%=choice%>">
                          <%=choice%>
                        </label>
                    </div>
                <%end%>
                <div class = "form-check form-margin-bottom">
                  <label class="form-check-label">
                    <input class = "form-check-input" checked = "true" type = "radio" name = "questionAnswer[<%=q.id%>]" value="/No Answer/">
                   (Leave Blank)
                  </label>
                </div>

             <% when 'yn' #yes-no %>
                <div class = "form-check">
                  <label class ="form-check-label thin">
                    <input class = "form-check-input" type = "radio" name = "questionAnswer[<%=q.id%>]" value = "Yes">
                    Yes
                  </label>
                </div>
                <div class = "form-check">
                  <label class ="form-check-label thin">
                    <input class = "form-check-input" type = "radio" name = "questionAnswer[<%=q.id%>]" value = "No">
                    No
                  </label>
                </div>
                <div class = "form-check form-margin-bottom">
                  <label class ="form-check-label">
                    <input class = "form-check-input" checked = "true" type = "radio" name = "questionAnswer[<%=q.id%>]" value = "/No Answer/">
                   (Leave Blank)
                  </label>
                </div>
             <% when 'tf' #true-false %>
                <div class = "form-check">
                  <label class ="form-check-label thin">
                    <input class = "form-check-input" type = "radio" name = "questionAnswer[<%=q.id%>]" value = "True">
                    True
                  </label>
                </div>
                <div class = "form-check">
                  <label class ="form-check-label thin">
                    <input class = "form-check-input" type = "radio" name = "questionAnswer[<%=q.id%>]" value = "False">
                    False
                  </label>
                  <div class = "form-check form-margin-bottom">
                    <label class ="form-check-label">
                      <input class = "form-check-input" checked = "true" type = "radio" name = "questionAnswer[<%=q.id%>]" value = "/No Answer/">
                     (Leave Blank)
                    </label>
                  </div>
                </div>
             <% when 'n' #number %>
                <input id="<%=q.id%>" type="number" name = "questionAnswer[<%=q.id%>]" class = "form-control form-margin-bottom" placeholder="Please enter a number">
            <% when 'h' #header %>
              <h3 class = "text-center question-header"><%=q.name%></h3>
							<input id="<%=q.id%>" name = "questionAnswer[<%=q.id%>]" style="display: none;"> 
                <hr />
            <%end%>
            </div>
      <% end %>
        <div style = "margin: 30px auto; display: block; text-align: center">
        <%= f.submit "Save and Submit!", class: "btn btn-primary" %>
        <%= link_to "Cancel", user_path(current_user.username), class: "btn btn-cancel" %>
        </div>
    <% end %>

  </div>
</div>

<style></style>

<script>
    boldChoice();
    window.addEventListener('click', boldChoice);
    function boldChoice(){
        var inputs = document.getElementsByClassName('form-check-input');
        for(var i = 0; i<inputs.length; i++){
            e = inputs.item(i);
            if(e.checked){
                e.parentNode.classList.remove('thin');
            }
            else{
                e.parentNode.classList.add('thin')
            }
        }
    }
</script>