config/routes.rb
Rails.application.routes.draw do

  # home/index/root page
  root 'front_page#index'

  # GET requests
  get '/about' => 'static_pages#about'
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'


  # POST requests
  post '/login' => 'sessions#create'

  resources :users, :param => :username
  resources :survey_completions

  # For JSON
  resources :surveys, :only => [:index, :show], :param => :name
  resources :questions, :only => [:show]

  resources :users, :only => [:show], :param => :username do
    resources :survey_completions, :only => [:new, :create, :delete]
    resources :local_surveys, :only => [:new, :create]
    resources :national_surveys, :only=> [:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
  has_many :question_answers, :dependent => :destroy

  validates :name, presence: true;
  validates :qtype, presence: true;
  validates :qorder, presence: true;
  validates :survey_id, presence: true;
end

app/models/question_answer.rb
class QuestionAnswer < ApplicationRecord
  belongs_to :survey_completion
  belongs_to :question
  validates :answer, numericality: true, if: Proc.new {|a| a.question.qtype == "n" && !a.answer.blank?}
  validates :survey_completion_id, presence: true
  validates :question_id, presence: true

end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :questions
  has_many :survey_completions
  default_scope -> { order(created_at: :desc) }

  validates :name, presence: true, :uniqueness => true

end

app/models/survey_completion.rb
class SurveyCompletion < ApplicationRecord
  belongs_to :user
  belongs_to :survey
  has_many :question_answers, :dependent => :destroy

  validates :user_id, presence: true
  validates :survey_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :survey_completions, :dependent => :destroy

  validates :username, :presence => true
  validates :username, :uniqueness => true
  validates :username, :format => {
    :with => /\A[a-zA-Z0-9_-]+\z/,
    :message => "Username can only have letters, numbers, -, and _"
  }
  validates :username, :exclusion => {
    :in => %w(new edit),
    :message => "%{value} is a reserved token. Please select another username."
  }
  validates :email, :presence => true
  validates :email, :uniqueness => true
  validates :email, :format => {
    :with => /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/,
    :message => "Please enter a vaild email address."
  }
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :position, :presence => true
  validates :password, :presence => true, :on => :new
  validates :password_confirmation, :presence => true, :on => :new

end

app/controllers/front_page_controller.rb
class FrontPageController < ApplicationController
  def index
    @answers = QuestionAnswer.all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def show
    @question = Question.find(params[:id])
		#Keys are used to identify a survey_completion if there are many from the same country
		@keys = Array.new 
		#Keys have a negative qorder.
		@question.survey.questions.each do |q|
			@keys.push q if q.qorder < 0
		end
		
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_username params[:user][:username]

    if user.nil?
      not_found("There is no account tied to that username. Please enter a valid username and password, or sign up to create an account.")
    elsif user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome, #{user.first_name}."
      redirect_to user_path(current_user.username)
    else
      flash[:error] = "Please enter a valid username and password."
      redirect_to login_path
    end
  end

  def destroy
    flash[:notice] = "Successfully logged out."
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  def index
    @surveys = Survey.all
    respond_to do |format|
      format.json
      format.xlsx {
        date = "#{Time.now.day}-#{Time.now.month}"
        response.headers['Content-Disposition'] = "attachment; filename= \"JB SET (#{date}).xlsx\""
      }
    end
  end

  def show
    @survey = Survey.find_by_name(params[:name])
    @lastCompletionTime;
    @lastCompletionCountry;
		
		# List of countres that have completed this survey
		@countries = []
		
    if @survey
			@survey.survey_completions.order(:updated_at).each do |sc|
				unless sc.question_answers.any? {|q| q.question.required && (q.answer.blank? || q.answer == "/No Answer/")}
					@countries.push sc.country
					@lastCompletionTime = sc.updated_at
					@lastCompletionCountry = sc.country
				end
			end
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, :except => [:new, :create]
  before_action :correct_user, :except => [:new, :create]

  def show
    @user = User.find_by_username(params[:username])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new create_params

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "This is your profile!  Click on survey below to take it."
      redirect_to user_path(current_user.username)
    else
      render :new
    end
  end

  def edit
    @user = User.find_by_username params[:username]
  end

  def update
    @user = User.find_by_username params[:username]

    if @user.update_attributes update_params
      flash[:success] = "Your profile information was successfully updated."
      redirect_to user_path(@user.username)
    else
      render :edit
    end
  end

  def destroy
    user = User.find_by_username params[:username]

    if user.destroy
      flash[:success] = "Your account was successfully deleted."
      redirect_to root_path
    else
      flash[:error] = "We were unable to delete your account at this time."
      redirect_back :fallback_location => users_path(@user.username)
    end
  end

  private
    def create_params
      params.require(:user).permit(
        :username,
        :first_name,
        :last_name,
        :email,
        :password,
        :password_confirmation,
        :position
      )
    end

    def update_params
      params.require(:user).permit(
        :first_name,
        :last_name,
        :email,
        :password,
        :password_confirmation,
        :position
      )
    end

    def correct_user
      @user = User.find_by_username(params[:username])
      redirect_to root_url unless current_user? @user

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def bootstrap_class_for flash_type
        case flash_type
        when "success"
            "alert-success"   # Green
        when "error"
            "alert-danger"    # Red
        when "alert"
            "alert-warning"   # Yellow
        when "notice"
            "alert-info"      # Blue
        else
            flash_type.to_s
        end
    end
end

app/helpers/front_page_helper.rb
module FrontPageHelper
end

app/helpers/national_surveys_helper.rb
module NationalSurveysHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/survey_completions_helper.rb
module SurveyCompletionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flashes.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in" >
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
 <% end %>
 

app/views/layouts/_footer.html.erb
<footer class="footer bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <p class="text-muted text-left"> 2017 JB SET</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header-home.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
            </button>
            <%= link_to "Home", root_path, class: "navbar-brand page-scroll" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Download", "/surveys.xlsx" %></li>
            <li><%= link_to "About / Help", about_path %></li>
              <% if current_user.nil? %>
              <li><%= link_to "Login", login_path %></li>
              <li><%= link_to "Sign Up", signup_path %></li>
              <% else %>
              <li><%= link_to "My Profile", user_path(current_user.username) %></li>
              <li><%= link_to "Log Out", logout_path %></li>
              <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JB SET | <%= yield(:title) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <meta name=viewport content="width=device-width, initial-scale=1.0">

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render :partial => "layouts/header-home" %>
    <div class= "container">
      <%= render :partial => "layouts/flashes" %>
      <%= yield %>
    <div style = "width: 300px; margin: auto">
      <h3>JB SET Playlist:</h3>
			<h5>(Because you guys are great)</h5>
      <iframe src="https://embed.spotify.com/?uri=spotify%3Auser%3A1241225324%3Aplaylist%3A2oZXu6fwEnctsOfKgViCJ9"
              width="300" height="380" frameborder="0" allowtransparency="true"></iframe>
      <h5 class="text-center">(by the way, you can totally add songs to this playlist. Add a song and we can all
        listen together!)</h5>
    </div>
    </div>
    <%= debug(params) if Rails.env.development? %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script>
        console.log("WIDTH= "+$('html').width());
    </script>
  </body>
</html>

app/views/layouts/front_page.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JB SET | <%= yield(:title) %></title>
    <%= stylesheet_link_tag    'front_page', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= csrf_meta_tags %>
    <meta name=viewport content="width=device-width, initial-scale=1.0">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <%= render :partial => "layouts/header-home" %>
      <%= yield %>
    <%= render :partial => "layouts/footer" %>
    <%= javascript_include_tag 'front_page', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/layouts/static_pages.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JB SET | <%= yield(:title) %></title>
    <%= stylesheet_link_tag    'static_pages', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= csrf_meta_tags %>
    <meta name=viewport content="width=device-width, initial-scale=1.0">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <%= render :partial => "layouts/header-home" %>
      <%= yield %>
    <%= render :partial => "layouts/footer" %>
    <%= javascript_include_tag 'static_pages', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/shared/_form_errors.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p>Please correct the following errors before proceeding:</p>
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li>
          <% if msg != "Is national can't be blank" %>
              <%= msg%>
          <% else %>
              <%= "Please select national or local" %>
          <%end%>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>